#!/usr/bin/env bash

if [ -z "$1" ]; then

  autocannon "https://localhost:5001/Spicy" -d 60 -c 500

else

  autocannon "https://localhost:5001/Spicy" -d 60 -c 500 --headers="Authorization: Bearer $1"
    
fi
